spring:
  mail:
    host: smtp.gmail.com
    username: ohmp3091@gmail.com
    password: mizldbvsxgfroept
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true