spring:
  mail:
    host: smtp.gmail.com
    username: ohmp3091@gmail.com
    password: afbzflasypazttfp
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  datasource:
    name: foodit
    url: jdbc:mysql://localhost:3306/foodit
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

